### ISSUE TITLE
[!] Invalid `Podfile` file: unexpected token at 'TypeError: Cannot read properties of undefined (reading 'configurations')

### ISSUE THREAD

**Issue by SohelKabir** [microsoft/react-native-macos#1613]
### Environment

```markdown
react-native -v: 70.6
npm ls react-native-macos: react-native-macos@0.68.59
node -v: 19
npm -v: 8.19.3
yarn --version: 1.22.19
xcodebuild -version: 14.1 (14B47b) (M1 Pro Macbook)
```

### Steps to reproduce the bug

trying to run `npx react-native-macos-init` on newly created react-native app for ios. ios app run perfectly but macos command failing. 

### Additional context

full error 

```
[!] Invalid `Podfile` file: unexpected token at 'TypeError: Cannot read properties of undefined (reading 'configurations')

    at Object.dependencyConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/react-native-macos/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)

    at /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:47:61

    at Array.reduce (<anonymous>)

    at getDependencyConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:44:51)

    at get react [as react] (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:99:18)

    at /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:16:51

    at Array.forEach (<anonymous>)

    at filterConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:15:38)

    at Object.func (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:27:32)

    at Command.handleAction (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli/build/index.js:142:23)

info Run CLI with --verbose flag for more details.
'.

 #  from /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/macos/Podfile:6
 #  -------------------------------------------
 #    platform :macos, '10.15'
 >    use_native_modules!
 #    use_react_native!(
 #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...
> pod install --repo-update

[!] Invalid `Podfile` file: unexpected token at 'TypeError: Cannot read properties of undefined (reading 'configurations')

    at Object.dependencyConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/react-native-macos/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)

    at /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:47:61

    at Array.reduce (<anonymous>)

    at getDependencyConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:44:51)

    at get react [as react] (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:99:18)

    at /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:16:51

    at Array.forEach (<anonymous>)

    at filterConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:15:38)

    at Object.func (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:27:32)

    at Command.handleAction (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli/build/index.js:142:23)

info Run CLI with --verbose flag for more details.
'.

 #  from /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/macos/Podfile:6
 #  -------------------------------------------
 #    platform :macos, '10.15'
 >    use_native_modules!
 #    use_react_native!(
 #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: unexpected token at 'TypeError: Cannot read properties of undefined (reading 'configurations')

    at Object.dependencyConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/react-native-macos/node_modules/@react-native-community/cli-platform-ios/build/config/index.js:102:37)

    at /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:47:61

    at Array.reduce (<anonymous>)

    at getDependencyConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:44:51)

    at get react [as react] (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/loadConfig.js:99:18)

    at /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:16:51

    at Array.forEach (<anonymous>)

    at filterConfig (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:15:38)

    at Object.func (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli-config/build/commands/config.js:27:32)

    at Command.handleAction (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/@react-native-community/cli/build/index.js:142:23)

info Run CLI with --verbose flag for more details.
'.

 #  from /Volumes/Office/TestProj/rn-mac-app/AwesomeProject/macos/Podfile:6
 #  -------------------------------------------
 #    platform :macos, '10.15'
 >    use_native_modules!
 #    use_react_native!(
 #  -------------------------------------------

Command failed: npx --quiet pod-install --non-interactive --quiet Error: Command failed: npx --quiet pod-install --non-interactive --quiet
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at installPods (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/react-native-macos/local-cli/generator-macos/index.js:136:16)
    at generateMacOS (/Volumes/Office/TestProj/rn-mac-app/AwesomeProject/node_modules/react-native-macos/local-cli/generate-macos.js:33:3)
    at Object.<anonymous> (/Users/sohelkabir/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:254:9)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/sohelkabir/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:10:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:442:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 54235,
  stdout: null,
  stderr: null
}
```

**Comment by steakknife** [comment]
react-native-macos maybe incompatible with 0.70.6

<details><summary><h1>Fails with 0.70.6</h1></summary>

```
# On Windows 11
npx react-native init fails                # Installs react-native 0.70.6
cd fails 
npx react-native-windows-init --overwrite
npx react-native autolink-windows          # Works
npx react-native-macos-init                # Installs react-native 0.68 and shows warnings about unmet peer dependencies
npx react-native autolink-windows          # Fails
```

</details>

<details><summary><h1>Works with 0.68.5 </h1></summary>

```
# On Windows 11
npx react-native init works --version 0.68.5
cd works
npx react-native-windows-init --overwrite
npx react-native autolink-windows              # Works
npx react-native-macos-init
npx react-native autolink-windows              # Works !
npx react-native run-windows                   # Also works: "Welcome to React Native" app appears
```

</detalis>

**Comment by Saadnajmi** [comment]
We only support up to 0.68 right now. The next macOS release will be 0.71 in the coming months
