### ISSUE TITLE
React Native fails installing pods

### ISSUE THREAD

**Issue by mazzo-l** [microsoft/react-native-macos#1738]
### Environment

```markdown
react-native -v: 9.5.0
npm ls react-native-macos: react-native-macos@0.68.66
node -v: v18.14.2
npm -v: 9.5.0
yarn --version: 1.22.19
xcodebuild -version: Xcode 14.1 Build version 14B47b
```

### Steps to reproduce the bug

I followed the steps as indicated in the [Get Started with macOS](https://microsoft.github.io/react-native-windows/docs/0.64/rnm-getting-started) section
```
npx react-native init project
cd project
npx react-native-macos-init
```
But after `npx react-native-macos-init` this happens:

```
Reading application name from package.json…
Reading react-native version from node_modules…
Reading react-native-macos version from node_modules…
Latest matching version of react-native-macos for react-native@0.71.3 is react-native-macos@0.68.66.
Installing react-native-macos@^0.68.0-0…
warning " > react-native-macos@0.68.66" has incorrect peer dependency "react@17.0.2".
warning "react-native-macos > react-shallow-renderer@16.14.1" has incorrect peer dependency "react@^16.0.0 || ^17.0.0".
warning "react-native-macos > use-subscription@1.5.1" has incorrect peer dependency "react@^16.8.0 || ^17.0.0".
react-native-macos@^0.68.0-0 successfully installed!
new macos/Podfile
new macos/.gitignore
new macos/project-iOS/AppDelegate.h
new macos/project-iOS/AppDelegate.m
new macos/project-iOS/Base.lproj/LaunchScreen.xib
new macos/project-iOS/Images.xcassets/AppIcon.appiconset/Contents.json
new macos/project-iOS/Images.xcassets/Contents.json
new macos/project-iOS/Info.plist
new macos/project-iOS/main.m
new macos/project-macOS/AppDelegate.h
new macos/project-macOS/AppDelegate.m
new macos/project-macOS/Assets.xcassets/AppIcon.appiconset/Contents.json
new macos/project-macOS/Assets.xcassets/Contents.json
new macos/project-macOS/Base.lproj/Main.storyboard
new macos/project-macOS/project.entitlements
new macos/project-macOS/Info.plist
new macos/project-macOS/ViewController.h
new macos/project-macOS/ViewController.m
new macos/project-macOS/main.m
new macos/project.xcodeproj/project.pbxproj
new macos/project.xcodeproj/xcshareddata/xcschemes/project-iOS.xcscheme
new macos/project.xcodeproj/xcshareddata/xcschemes/project-macOS.xcscheme
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1452:in `rescue in block in activate_dependencies': Could not find 'rexml' (>= 0) among 116 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/mazzo/.rvm/gems/ruby-2.7.6:/Users/mazzo/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0:/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec' at: /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/specifications/CFPropertyList-3.0.6.gemspec, execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1449:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1420:in `activate'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1456:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1420:in `activate'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1456:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1420:in `activate'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:284:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'
/opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/dependency.rb:314:in `to_specs': Could not find 'rexml' (>= 0) among 116 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/mazzo/.rvm/gems/ruby-2.7.6:/Users/mazzo/.rvm/rubies/ruby-2.7.6/lib/ruby/gems/2.7.0:/opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec' , execute `gem env` for more information
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1450:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1420:in `activate'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1456:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1420:in `activate'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1456:in `block in activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `each'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1438:in `activate_dependencies'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems/specification.rb:1420:in `activate'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:284:in `block in activate_bin_path'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `synchronize'
	from /opt/homebrew/Cellar/ruby/3.2.1/lib/ruby/3.2.0/rubygems.rb:283:in `activate_bin_path'
	from /opt/homebrew/Cellar/cocoapods/1.11.3_1/libexec/bin/pod:25:in `<main>'
› Attempting to install CocoaPods CLI with Gem
Fetching fuzzy_match-2.0.4.gem
Fetching activesupport-6.1.7.2.gem
Fetching zeitwerk-2.6.7.gem
Fetching i18n-1.12.0.gem
Fetching nap-1.1.0.gem
Fetching tzinfo-2.0.6.gem
Fetching httpclient-2.8.3.gem
Fetching concurrent-ruby-1.2.2.gem
Fetching algoliasearch-1.27.5.gem
Fetching ffi-1.15.5.gem
Fetching ethon-0.16.0.gem
Fetching typhoeus-1.4.0.gem
Fetching netrc-0.11.0.gem
Fetching public_suffix-4.0.7.gem
Fetching addressable-2.8.1.gem
Fetching cocoapods-core-1.11.3.gem
Fetching claide-1.1.0.gem
Fetching cocoapods-deintegrate-1.0.5.gem
Fetching cocoapods-downloader-1.6.3.gem
Fetching cocoapods-plugins-1.0.0.gem
Fetching cocoapods-search-1.0.1.gem
Fetching cocoapods-trunk-1.6.0.gem
Fetching cocoapods-try-1.2.0.gem
Fetching molinillo-0.8.0.gem
Fetching atomos-0.1.3.gem
Fetching rexml-3.2.5.gem
Fetching CFPropertyList-3.0.6.gem
Fetching colored2-3.1.2.gem
Fetching nanaimo-0.3.0.gem
Fetching xcodeproj-1.22.0.gem
Fetching escape-0.0.4.gem
Fetching fourflusher-2.3.1.gem
Fetching gh_inspector-1.1.3.gem
Fetching ruby-macho-2.5.1.gem
Fetching cocoapods-1.11.3.gem
Successfully installed concurrent-ruby-1.2.2
Successfully installed i18n-1.12.0
Successfully installed tzinfo-2.0.6
Successfully installed zeitwerk-2.6.7
Successfully installed activesupport-6.1.7.2
Successfully installed nap-1.1.0
Successfully installed fuzzy_match-2.0.4
Successfully installed httpclient-2.8.3
A new major version is available for Algolia! Please now use the https://rubygems.org/gems/algolia gem to get the latest features.
Successfully installed algoliasearch-1.27.5
Building native extensions. This could take a while...
Successfully installed ffi-1.15.5
Successfully installed ethon-0.16.0
Successfully installed typhoeus-1.4.0
Successfully installed netrc-0.11.0
Successfully installed public_suffix-4.0.7
Successfully installed addressable-2.8.1
Successfully installed cocoapods-core-1.11.3
Successfully installed claide-1.1.0
Successfully installed cocoapods-deintegrate-1.0.5
Successfully installed cocoapods-downloader-1.6.3
Successfully installed cocoapods-plugins-1.0.0
Successfully installed cocoapods-search-1.0.1
Successfully installed cocoapods-trunk-1.6.0
Successfully installed cocoapods-try-1.2.0
Successfully installed molinillo-0.8.0
Successfully installed atomos-0.1.3
Successfully installed rexml-3.2.5
Successfully installed CFPropertyList-3.0.6
Successfully installed colored2-3.1.2
Successfully installed nanaimo-0.3.0
Successfully installed xcodeproj-1.22.0
Successfully installed escape-0.0.4
Successfully installed fourflusher-2.3.1
Successfully installed gh_inspector-1.1.3
Successfully installed ruby-macho-2.5.1
Successfully installed cocoapods-1.11.3
35 gems installed
› Successfully installed CocoaPods CLI with Gem
> pod install

[!] Invalid `Podfile` file: unexpected token at 'Error: Package name not found in /Users/mazzo/Desktop/progetti/react_native/project/android/app/src/main/AndroidManifest.xml

    at Object.projectConfig (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/react-native-macos/node_modules/@react-native-community/cli-platform-android/build/config/index.js:74:11)

    at get project [as project] (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/loadConfig.js:64:50)

    at filterConfig (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/commands/config.js:11:20)

    at Object.func (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/commands/config.js:25:32)

    at Command.handleAction (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/build/index.js:108:23)

    at Command.listener [as _actionHandler] (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:482:17)

    at /Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:65

    at Command._chainOrCall (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1177:12)

    at Command._parseCommand (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:27)

    at /Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1081:27

info Run CLI with --verbose flag for more details.
'.

 #  from /Users/mazzo/Desktop/progetti/react_native/project/macos/Podfile:6
 #  -------------------------------------------
 #    platform :macos, '10.15'
 >    use_native_modules!
 #    use_react_native!(
 #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...
> pod install --repo-update

[!] Invalid `Podfile` file: unexpected token at 'Error: Package name not found in /Users/mazzo/Desktop/progetti/react_native/project/android/app/src/main/AndroidManifest.xml

    at Object.projectConfig (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/react-native-macos/node_modules/@react-native-community/cli-platform-android/build/config/index.js:74:11)

    at get project [as project] (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/loadConfig.js:64:50)

    at filterConfig (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/commands/config.js:11:20)

    at Object.func (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/commands/config.js:25:32)

    at Command.handleAction (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/build/index.js:108:23)

    at Command.listener [as _actionHandler] (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:482:17)

    at /Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:65

    at Command._chainOrCall (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1177:12)

    at Command._parseCommand (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:27)

    at /Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1081:27

info Run CLI with --verbose flag for more details.
'.

 #  from /Users/mazzo/Desktop/progetti/react_native/project/macos/Podfile:6
 #  -------------------------------------------
 #    platform :macos, '10.15'
 >    use_native_modules!
 #    use_react_native!(
 #  -------------------------------------------
Couldn't install Pods. Updating the Pods project and trying again...
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: unexpected token at 'Error: Package name not found in /Users/mazzo/Desktop/progetti/react_native/project/android/app/src/main/AndroidManifest.xml

    at Object.projectConfig (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/react-native-macos/node_modules/@react-native-community/cli-platform-android/build/config/index.js:74:11)

    at get project [as project] (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/loadConfig.js:64:50)

    at filterConfig (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/commands/config.js:11:20)

    at Object.func (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli-config/build/commands/config.js:25:32)

    at Command.handleAction (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/build/index.js:108:23)

    at Command.listener [as _actionHandler] (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:482:17)

    at /Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:65

    at Command._chainOrCall (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1177:12)

    at Command._parseCommand (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1283:27)

    at /Users/mazzo/Desktop/progetti/react_native/project/node_modules/@react-native-community/cli/node_modules/commander/lib/command.js:1081:27

info Run CLI with --verbose flag for more details.
'.

 #  from /Users/mazzo/Desktop/progetti/react_native/project/macos/Podfile:6
 #  -------------------------------------------
 #    platform :macos, '10.15'
 >    use_native_modules!
 #    use_react_native!(
 #  -------------------------------------------

Command failed: npx --quiet pod-install --non-interactive --quiet Error: Command failed: npx --quiet pod-install --non-interactive --quiet
    at checkExecSyncError (node:child_process:885:11)
    at Object.execSync (node:child_process:957:15)
    at installPods (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/react-native-macos/local-cli/generator-macos/index.js:136:16)
    at generateMacOS (/Users/mazzo/Desktop/progetti/react_native/project/node_modules/react-native-macos/local-cli/generate-macos.js:33:3)
    at Object.<anonymous> (/Users/mazzo/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:254:9)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/mazzo/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:10:58)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processImmediate (node:internal/timers:447:9) {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 93642,
  stdout: null,
  stderr: null
}
```

Even though I'm trying to build for macOS, the Podfile seems to fail while attempting to do something with Android files.

### Additional context

I'm using a M2 MacBook Air

**Comment by jkoutavas** [comment]
I'm seeing this error too. Any update / workaround for this?

**Comment by Saadnajmi** [comment]
I ran into this as well, I'll update if I learn anything.

**Comment by Saadnajmi** [comment]
So this happens when you're `react-native.config.js` file is not properly configured:
> [!] Invalid `Podfile` file: unexpected token at 'Error: Package name not found in /Users/mazzo/Desktop/progetti/react_native/project/android/app/src/main/AndroidManifest.xml

As far as I can tell, running `pod install` calls a ruby method that calls `react-native config`, which fails.

Could you print out the output of `npc react-native config` and/or your `react-native.config.js` file?

**Comment by upscripter** [comment]
> Could you print out the output of npc react-native config and/or your react-native.config.js file?

`command not found: npc`

Where can I find `react-native.config.js`?

**Comment by Saadnajmi** [comment]
Ah.. the template project doesn't have one. Interesting. Can you try creating one that looks something like this, putting fit in the root of your repo, then running `npx react-native config` and see if you still get an error?


```js

const ios = require('@react-native-community/cli-platform-ios');
const android = require('@react-native-community/cli-platform-android');

module.exports = {
  commands: [...ios.commands, ...android.commands],
  platforms: {
    ios: {
      projectConfig: ios.projectConfig,
      dependencyConfig: ios.dependencyConfig,
    },
    android: {
      projectConfig: android.projectConfig,
      dependencyConfig: android.dependencyConfig,
    },
  },
  reactNativePath: '../../',
  project: {
    ios: {
      // React Native macOS uses the iOS key in it's config ¯\_(ツ)_/¯
      sourceDir: 'macos',
    },
    android: {
      sourceDir: 'android',
    }
  },
};
```

**Comment by upscripter** [comment]
Same error:

> Error: Package name not found in /Users/macbook/Documents/dev/macApp/android/app/src/main/AndroidManifest.xml
    at Object.projectConfig ...

**Comment by SyedTayyabUlMazhar** [comment]
> [!] Invalid Podfile file: unexpected token at 'Error: Package name not found in /Users/mazzo/Desktop/progetti/react_native/project/android/app/src/main/AndroidManifest.xml

Shouldn't there be a package name in AndroidMainifest.xml?

**Comment by upscripter** [comment]
> Shouldn't there be a package name in AndroidMainifest.xml?

android/app/src/main/AndroidManifest.xml: https://pastebin.com/tDeRjhWB

There's no package name in my case. It's a clear setup from https://aka.ms/ReactNativeGuideMacOS

node -v: v20.0.0
npm -v: 9.6.4
yarn --version: 1.22.19
xcodebuild -version: Xcode 14.3 Build version 14E222b
I'm using a M1 MacBook Air

**Comment by SyedTayyabUlMazhar** [comment]
> > Shouldn't there be a package name in AndroidMainifest.xml?
> 
> android/app/src/main/AndroidManifest.xml: https://pastebin.com/tDeRjhWB
> 
> There's no package name in my case. It's a clear setup from https://aka.ms/ReactNativeGuideMacOS
> 
> node -v: v20.0.0 npm -v: 9.6.4 yarn --version: 1.22.19 xcodebuild -version: Xcode 14.3 Build version 14E222b I'm using a M1 MacBook Air

It seems that they changed how package name is added [link](https://github.com/facebook/react-native/commit/cec9a34f6cd2a82bba76e15761da6b588bc3f574)

**Comment by upscripter** [comment]
I get the same error with [0.72.0-RC.1](https://github.com/facebook/react-native/releases/tag/v0.72.0-rc.1)

**Comment by Saadnajmi** [comment]
> I get the same error with [0.72.0-RC.1](https://github.com/facebook/react-native/releases/tag/v0.72.0-rc.1) 

We don't support 0.72 yet, only up to 0.71 at the moment.

**Comment by upscripter** [comment]
> We don't support 0.72 yet, only up to 0.71 at the moment.

But it doesn't work with 0.71 also. So, what can I do to fix it? Is it only for me or for everyone?

**Comment by Saadnajmi** [comment]
I was able to run the react-native-macos-init+ pod install successfully recently, so I think this is fixed with the latest version of both RN-macOS 71 and react-native-macos-init? Could you try testing again?

**Comment by jkoutavas** [comment]
@Saadnajmi `npx react-native init MyApp --template react-native@^0.71` works fine now, thanks.

New issue, when I do `npc react-native run-macos`, I get this LogBox error:

<img width="487" alt="image" src="https://github.com/microsoft/react-native-macos/assets/1264625/473ac53b-4828-42f7-b8e9-d3883d156687">
