### ISSUE TITLE
Adding macos to newly created react-native project

### ISSUE THREAD

**Issue by Sirojiddin96** [microsoft/react-native-macos#1798]
I have followed and created new project based on npx react-native init with version 0.71.0. I could add windows successfull, however, When I run npx react-native-macos-init I got following errors:

Latest matching version of react-native-macos for react-native@0.71.0 is react-native-macos@0.68.70.
Upgrading to react-native-macos@^0.68.0-0…
Command failed: npm install --save --silent "react-native-macos@^0.68.0-0" Error: Command failed: npm install --save --silent "react-native-macos@^0.68.0-0"
    at checkExecSyncError (node:child_process:871:11)
    at Object.execSync (node:child_process:943:15)
    at Object.<anonymous> (/Users/l20220098/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:247:29)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/l20220098/.npm/_npx/20f1505fae2cef5b/node_modules/react-native-macos-init/lib-commonjs/cli.js:10:58) {
  status: 1,
  signal: null,
  output: [ null, <Buffer >, <Buffer > ],
  pid: 68086,
  stdout: <Buffer >,
  stderr: <Buffer >
}

How can I solve this issue? I could not find any resource for it.
Thank you.
 "react": "18.2.0",
 "react-native": "0.71.0",

**Comment by Sirojiddin96** [comment]
It is working. Thank you
