### ISSUE TITLE
Getting MODULE_NOT_FOUND error on npx react-native-macos-init

### ISSUE THREAD

**Issue by YajanaRao** [microsoft/react-native-macos#804]
### Environment

1. `react-native -v`:
3. `npm ls react-native-macos`: react-native-macos@0.63.37 extraneous
4. `node -v`: v12.14.1
5. `npm -v`: 7.19.1
6. `yarn --version`: 1.22.10
7. `xcodebuild -version`:
Xcode 12.3
Build version 12C33

### Steps to Reproduce

(Write your steps here:)

1. npx react-native init Serenity --template react-native@^0.63.0
2. cd Serenity
3. npx react-native-macos-init

### Expected Behavior

(Write what you thought would happen.)

### Actual Behavior

(Write what happened. Add screenshots!)
```
Cannot find module '/Users/yajanarao/Projects/desktop/Serenity/node_modules/chalk/source'. Please verify that the package.json has a valid "main" entry Error: Cannot find module '/Users/yajanarao/Projects/desktop/Serenity/node_modules/chalk/source'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:297:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:528:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:27)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/yajanarao/Projects/desktop/Serenity/node_modules/react-native-macos/local-cli/generator-macos/index.js:5:15)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/yajanarao/Projects/desktop/Serenity/node_modules/chalk/package.json',
  requestPath: 'chalk'
}
```

**Comment by Saadnajmi** [comment]
Just checking.. did you do a `npm install` or `yarn install` in between steps 2 and 3 ?

**Comment by YajanaRao** [comment]
Deleting yarn.lock and yarn install resolved the issue. Thank you @Saadnajmi .
